### PR TITLE
Make WorkspaceReferencesParams.query partial

### PR DESCRIPTION
**Pull request by felixfbecker**

### CODE REVIEW

**Comment by emidoots** [comment]
Where can I read about what this does? I Googled a little bit but only came up with mixins etc

**Comment by beyang** [comment]
@slimsag see discussion here: https://github.com/Microsoft/TypeScript/issues/4889.

I think this is not strictly necessary to make things typesafe, but it does provide a hint to the consumer of the spec that not all the fields have to be present in the query.

**Comment by felixfbecker** [comment]
It makes all properties optional.
Docs here: https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types
In my case it is pretty important to know whether all fields I define (which includes a unqiue symbol ID) will be present or not, so I thought it would be good to clear it up in the spec

**Comment by emidoots** [comment]
LGTM

**Review by emidoots — APPROVED** [review]

**Comment by emidoots** [comment]
Thanks for the links, BTW!

**Pull request merged**
