### PR TITLE
Specify how a client can deny an xcontent request

### PR DESCRIPTION
**Pull request by nemethf**
I haven't found a way to create an issue, so I've formulated my question as a proposal. 
How should a client deny a textDocument/xcontent request?
Thanks.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Could you elaborate for which reason the server would "deny" the request?

**Comment by nemethf** [comment]
I'm sorry if I wasn't clear, I talked about the client and not the server.  The text already says: "The client may choose whether or not to satisfy these requests."  I just don't  know what  the client should do when it chooses not to satisfy a textDocument/xcontent request.  As for a reason,  if the server asks for the content of /etc/shadow, then the client might want to refrain from sharing the passwords with the server. 

Thanks.

**Comment by felixfbecker** [comment]
Thanks for the example. `InvalidRequest` should not be used for this, as it is defined in JSON RPC spec:

> code | message | meaning
> -- | -- | --
> -32600 | Invalid Request | The JSON sent is not a valid Request object.

https://www.jsonrpc.org/specification#error_object

The client would specify its own error code in the range -32000 to -32099, which is reserved for implementation-specific error codes.

**Comment by nemethf** [comment]
So if I want to implement the files extension in a client, then how should I handle this case?  Should I choose an arbitrary error code in that range?  I hope we can extend the specification with something specific.

**Comment by felixfbecker** [comment]
Yeah. There a lot of different errors that can happen when reading files (permission errors, file not found, locks, too many open files, ...) and xfiles might not even be backed by the file system, for example it could be backed by HTTP, which would have its entire own class of errors, plus network errors etc. It is difficult to spec these all out, and in this case a server is best in just catching all errors and handling them the same way without caring about specific error codes. I.e. from the server's perspective, all it should care about is "did fetching this file succeed or not". The error message can still contain error details for humans.

**Comment by nemethf** [comment]
OK.  Thank you for the clarification.  I close this PR then.

By the way, have you submitted this extension to upstream?  I think this is a very useful one.

**Pull request closed without merging**
